### ISSUE TITLE
[Question] Any reason why it's not in Scoop Known Bucket?

### ISSUE THREAD

**Issue by LazyGeniusMan** [twpayne/scoop-bucket#2]
Hi, is there any reason why this is not on Scoop Known bucket? I also notice that you update the app manifest manually? In case you didn't know Scoop now have autoupdate feature using github action on their repo. I could make a PR on Scoop Known bucket and add chezmoi if you dont mind.

**Comment by twpayne** [comment]
The manifest is automatically generated and pushed by [GoReleaser](https://goreleaser.com/customization/scoop/) as part of chezmoi's build process.

I've opened https://github.com/ScoopInstaller/Main/issues/3220 to request adding chezmoi as a Scoop Main bucket.

**Comment by LazyGeniusMan** [comment]
Done, you might want to update documentation for installing with scoop since now without adding this bucket it will work too, the caveat for using known bucket is the update will a bit slower compared to this bucket using GoReleaser since scoop autoupdate github action trigger every 4 hours

**Comment by twpayne** [comment]
Thanks! I updated the install documentation in https://github.com/twpayne/chezmoi/commit/f7deac3facc2a4d88d7561fc18f2d371517b94c7.
